
export const enum Actions{
    SWITCH_THEME = "SWITCH_THEME",
    LOG_USER_API = "LOG_USER_API",
    REG_USER_API = "REG_USER_API",
    GET_USER_API = "GET_USER_API",
    GET_CURRENT_USER_API = "GET_CURRENT_USER_API",
    SET_MODAL_OPEN = "SET_MODAL_OPEN",
    CHANGE_MODAL_NUM = "CHANGE_MODAL_NUM",
    SET_PROFILE = 'SET_PROFILE',
    CLEAR_PROFILE = 'CLEAR_PROFILE',
    SET_FETCH = 'SET_FETCH',
    CLEAR_FETCH = 'CLEAR_FETCH',
    SET_SIGN_NICKNAME = 'SET_SIGN_NICKNAME',
    SET_SIGN_EMAIL = 'SET_SIGN_EMAIL',
    CHECK_SIGN_NICKNAME = 'CHECK_SIGN_NICKNAME',
    CHECK_SIGN_EMAIL = 'CHECK_SIGN_EMAIL',
    CLEAR_SIGN = 'CLEAR_SIGN',
    SEND_EMAIL = 'SEND_EMAIL',
    SEND_CODE = 'SEND_CODE',
    SET_CURRENT_PROFILE = "SET_CURRENT_PROFILE",
    CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE",
}


