
export const enum Actions{
    SWITCH_THEME = "SWITCH_THEME",
    LOG_USER_API = "LOG_USER_API",
    REG_USER_API = "REG_USER_API",
    GET_USER_API = "GET_USER_API",
    SET_MODAL_OPEN = "SET_MODAL_OPEN",
    CHANGE_MODAL_NUM = "CHANGE_MODAL_NUM",
    SET_PROFILE = 'SET_PROFILE',
    CLEAR_PROFILE = 'CLEAR_PROFILE',
    SET_FETCH = 'SET_FETCH',
    CLEAR_FETCH = 'CLEAR_FETCH'
}


